### ISSUE TITLE
Not socks4 or socks5?

### ISSUE THREAD

**Issue by tom-spalding** [Morhaus/socks-handler#1]
Hi, sometimes [`version`](https://github.com/Morhaus/socks-handler/blob/master/src/index.coffee#L6) doesn't return [socks4.VERSION](https://github.com/Morhaus/socks-handler/blob/master/src/index.coffee#L7) or [socks5.VERSION](https://github.com/Morhaus/socks-handler/blob/master/src/index.coffee#L9). When it doesn't, it returns 67 and 71. 

```
     error socks
           Unsupported SOCKS version: 71
     error socks
           Unsupported SOCKS version: 67
```

**Comment by alexkirsz** [comment]
71 often means the proxy is receiving raw HTTP data (GET, G == 71).
67 might be the HTTP CONNECT method (C == 67).
So an HTTP client is basically trying to use your socks server as an HTTP server/proxy.

**Comment by codingonHP** [comment]
@alexkirsz  I am getting "67 might be the HTTP CONNECT method (C == 67)" error because I am doing CONNECT localhost:8010. How do I connect to the server if not this way?

[Solved]
I finally understood how SOCKs work
http://www.faqs.org/rfcs/rfc1928.html

**Comment by tom-spalding** [comment]
ha ok thanks!
